### ISSUE TITLE
Stencil: build doesn't work on nx 15.9.x

### ISSUE THREAD

**Issue by marcincichocki** [nxext/nx-extensions-ionic#10]
**Describe the bug**
`@nxext/stencil:build` does not work after update to nx 15.9.x. Error message is shown: 
```sh
Cannot find module '@nrwl/workspace/src/utilities/ast-utils'
```

**To Reproduce**
Try to build project with latest nx

**Expected behavior**
Executor should work as before.

**Additional context**
Looks like this file: https://github.com/nxext/nx-extensions/blob/main/packages/stencil/src/utils/ast-utils.ts#L4 is importing file that does not exist anymore. It was moved: https://github.com/nrwl/nx/pull/15540/files#diff-6a3ae3fda9f50d1b43708469ef9af795224222b10b7b4802b561da5529d6db12
